version: 2

multi-ecosystem-groups:
  maintenance:
    schedule:
      interval: "monthly"
      time: "06:00"
      day: "monday"
      timezone: "America/Detroit"
    commit-message:
      prefix: "Monthly dependency updates: "
    assignees: ["erinesullivan"]


updates:
  # For npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    multi-ecosystem-group: "maintenance"
    patterns: ["*"]

  # For GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "maintenance"
    patterns: ["*"]

  # For Docker updates
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "maintenance"
    patterns: ["*"]
